### ISSUE TITLE
Can we get a colored mesh from the trained model?

### ISSUE THREAD

**Issue by endlesswho** [dazinovic/neural-rgbd-surface-reconstruction#10]
Original NeRF can simulate a virtual camera for extract the vertices color from the NeRF, I did the same operation as https://github.com/bmild/nerf/issues/44 , but get a bad results, any ideas to extract color mesh from the trained model?

**Comment by dazinovic** [comment]
For each vertex, you could shoot a ray along the normal direction and integrate the color samples.

**Comment by sanbuddhacharyas** [comment]
@endlesswho did you generate coloured mesh from the trained model. If yes then please help me too.

> Original NeRF can simulate a virtual camera for extract the vertices color from the NeRF, I did the same operation as [bmild/nerf#44](https://github.com/bmild/nerf/issues/44) , but get a bad results, any ideas to extract color mesh from the trained model?

**Comment by endlesswho** [comment]
> @endlesswho did you generate coloured mesh from the trained model. If yes then please help me too.
> 
> > Original NeRF can simulate a virtual camera for extract the vertices color from the NeRF, I did the same operation as [bmild/nerf#44](https://github.com/bmild/nerf/issues/44) , but get a bad results, any ideas to extract color mesh from the trained model?
> 
> 

The result is a mess. Maybe mycode have bugs. I use mvs_texturing for texture mapping.

**Comment by dazinovic** [comment]
Don't expect amazing color predictions. They are just enough to improve the geometry through the photometric loss. The best you can do is shoot a short ray through every vertex using the a view direction that is opposite of the vertex normal. Alternatively, project the vertices into the photographs and take the average color.

**Comment by qpc001** [comment]
will it output the optimized pose?

**Comment by waveviewer** [comment]
> will it output the optimized pose?

@qpc001  Yes, usage in `extract_optimized_poses.py`

**Comment by Ceciliammm** [comment]
Has anyone built the textured mesh? and how should it be done
