### ISSUE TITLE
Can't find piece of code that normalizes predicted sdf to lie between -1 and 1

### ISSUE THREAD

**Issue by andrewsonga** [dazinovic/neural-rgbd-surface-reconstruction#15]
Hello,

I'm trying to follow up on the discussion in issue #12 about how the predicted SDF is defined (i.e. whether it is defined in the metric space or the normalized space [-1, 1]). You mentioned that "predicted SDF is always normalized between -1 (behind the surface) and +1 (in front of the surface)". However, I couldn't find anywhere in the code where the SDF output from the NeRF MLP is explicitly constrained to fall within the range [-1, 1] (for e.g. via a tanh activation) - there does not seem to be any activation applied when computing `alpha_out` in the function `init_nerf_model` from https://github.com/dazinovic/neural-rgbd-surface-reconstruction/blob/44ccc8a94b6b62be46d116c9fe49e95f528fbad9/nerf_helpers.py#L106-L116.

Could you please direct me to where exactly in the codebase the predicted SDF is normalized?
Thank you in advance!

**Comment by dazinovic** [comment]
There is no explicit normalization. The freespace and truncation losses push the predicted SDF towards the [-1, 1] range.
