### ISSUE TITLE
How to make own datasets?

### ISSUE THREAD

**Issue by divingwolf** [dazinovic/neural-rgbd-surface-reconstruction#16]
Hello, author.

Thank you for completing and providing this great work.

I ran the code and got perfect results on the data set you provided, so I want to try to make my own data set and see how the code works. Could you describe in detail how to create own datasets, such as how to use BundleFusion you mentioned in readme.md.

**Comment by IsaacYaner** [comment]
Hello, @jinshuitiaofan may I ask how did you prepare the data folder? I have downloaded the datasets but I have no idea how to prepare the files listed in data section such as:
    ├── depth0.png   
    ├── img1.png
    ├── focal.txt  
    ├── poses.txt  
    ├── trainval_poses.txt

**Comment by jinshuitiaofan** [comment]
> Hello, @jinshuitiaofan may I ask how did you prepare the data folder? I have downloaded the datasets but I have no idea how to prepare the files listed in data section such as: ├── depth0.png ├── img1.png ├── focal.txt ├── poses.txt ├── trainval_poses.txt

haha, I dont know. The author has not replied to me yet.

**Comment by IsaacYaner** [comment]
I think I figured it out thanks all:)

**Comment by jinshuitiaofan** [comment]
> I think I figured it out thanks all:)

bro, show me your achievement. :)

**Comment by Daniil-Osokin** [comment]
Hi! You should organize it in the following way, as [README.md](https://github.com/dazinovic/neural-rgbd-surface-reconstruction#data) says:
```
<scene_name>            # datadir in the config file
├── depth
    ├── leave empty
    ...
├── depth_filtered      # your depth images
    ├── depth0.png     
    ├── depth1.png
    ├── depth2.png
    ...
├── images              # your RGB images
    ├── img0.png     
    ├── img1.png
    ├── img2.png
    ...
├── focal.txt           # your camera focal length
├── trainval_poses.txt  # your camera poses for optimization
```
