### ISSUE TITLE
How to Transform ScanNet Poses?

### ISSUE THREAD

**Issue by wtiandong** [dazinovic/neural-rgbd-surface-reconstruction#2]
Hi @dazinovic ,
Thanks for your great work! I'm trying to train a ScanNet Scene using your code. Could you tell me how you transform ScanNet poses? I investigate the synthesis dataset you provide, I guess trainval_poses are:
[ 1 0 0 0 
  0 0 -1 0
  0 1 0 0
  0 0 0 1] @ inv(T0) @ Tx
where T0 is the first pose of poses(poses.txt) and Tx is the rest. But they are not equal after I verify the "complete kitchen" scene.

Thanks.

**Comment by dazinovic** [comment]
Hi wtiandong,

poses.txt contains the ground truth poses for the scenes. trainval_poses.txt contains poses predicted by BundleFusion. The BundleFusion trajectory will not perfectly match the ground truth trajectory.

If you would like to test the code on the official ScanNet data, you can preprocess the poses like this:

T0 @ scannet_pose @ T1

T0 = [ 1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.]

T1 = array([[ 1.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  0.],
       [ 0.,  0., -1.,  0.],
       [ 0.,  0.,  0.,  1.]])

**Comment by wtiandong** [comment]
Hi dazinovic , 
Thank you very much!

**Comment by cwchenwang** [comment]
Hi, @dazinovic, I am also trying your code on Scannet data. How will the results differ if I use Scannet official poses or BundleFusion pose? And I noticed that in your load_scannet, fx = fy is assumed, but that is not true in the Scannet offical data, what is the proper way to tackle this?

**Comment by chensjtu** [comment]
@wtiandong can you post your result on scannet? I'm afraid I get the wrong results.

**Comment by soumyadipm** [comment]
@cwchenwang @wtiandong @dazinovic Can you guys please help me to run this code on ScanNet? Struggling for last two weeks.

**Comment by wtiandong** [comment]
> @cwchenwang @wtiandong @dazinovic Can you guys please help me to run this code on ScanNet? Struggling for last two weeks.

Sorry, It's a long time since I opened this issue. I look up in my notebook but there seems nothing about that. maybe I didn't record this. I will try to find some code of mine that could help, but I can't guarantee.
