### ISSUE TITLE
Result with real-world dataset is a mass, possible reasons

### ISSUE THREAD

**Issue by CherniGhassen** [dazinovic/neural-rgbd-surface-reconstruction#21]
Hi, 

When I run the model on my own dataset, I get a mass as you can see below. 
Is it because of the translation/scaling factors that are applied? Or maybe because of the format of the poses that I use?
From what I have seen in previous questions, when the pose is wrong, people still get a sort of distorted mesh.

I would really appreciate your help!

![mass](https://user-images.githubusercontent.com/107480734/179753794-4370e9ed-1a22-49e5-b8cc-90c1042a75e6.png)

**Comment by dazinovic** [comment]
Most likely the poses you used are incorrect. The project assumes OpenGL-style poses. I would suggest visualizing the rays that were generated with the provided poses to see if they make sense.
