### ISSUE TITLE
Differences between poses.txt and tranval_poses.txt

### ISSUE THREAD

**Issue by zParquet** [dazinovic/neural-rgbd-surface-reconstruction#23]
Hello, thanks for your excellant work! I have some questions about the differences between poses.txt and tranval_poses.txt
I know that poses.txt are ground truth poses while tranval_poses.txt are estimated poses from BundleFusion. However, the difference between the two is a little too big. For example, the second image's camera pose:

from poses.txt:
0.998570 0.027344 -0.045941 -0.290765
0.000823 0.851353 0.524586 1.367835
0.053458 -0.523881 0.850117 1.462237
0.000000 0.000000 0.000000 1.000000

from tranval_poses.txt:
0.999972 -0.00450333 0.00597531 0.0134453
0.00598022 0.00107819 -0.999981 0.000717199
0.0044968 0.999989 0.00110513 -0.0021637
0 0 0 1

It seems that the the ground truth camera directions and origins are totally different from the estimated ones, and the numerical differences are not because of estimating but systematic operations. I tried to use poses.txt to train and get totally bad results. Therefore, I wonder if  there are any other transformations from the GT pose format to the trainval pose format? 
Looking forward to your reply. Thanks!

**Comment by dazinovic** [comment]
The poses in trainval_poses.txt start with an identity pose. You might need to adjust the translation parameter in the config file if you train with the GT poses.

**Comment by zParquet** [comment]
I will later try it. Thanks for your reply!
