### ISSUE TITLE
Get noisy results 

### ISSUE THREAD

**Issue by ShawnXu10** [dazinovic/neural-rgbd-surface-reconstruction#27]
Just I run you code to reconstruct scenes but getting some pretty weird and different results.
For example, the green room.

<img width="1253" alt="Screen Shot 2022-08-30 at 10 41 47 AM" src="https://user-images.githubusercontent.com/19980426/188011590-f70667df-9ab2-4cdd-afdd-9ba2ea88af58.png">
<img width="1250" alt="Screen Shot 2022-08-30 at 10 42 20 AM" src="https://user-images.githubusercontent.com/19980426/188011593-25e5ea2a-ff2e-48b4-bd31-417e14cf2ef7.png">

The right is output from you code and the second is the mesh you provided
Seem the right has much more vertices and covered by outliers. Are there any post-processes you did that not includes in the code?

**Comment by dazinovic** [comment]
You need to cull the mesh. Perhaps this reply can help you: https://github.com/dazinovic/neural-rgbd-surface-reconstruction/issues/13#issuecomment-1129218530

**Comment by ShawnXu10** [comment]
> 

It solves my problem. Thank you.
