### ISSUE TITLE
release scannet experiment data

### ISSUE THREAD

**Issue by Guptajakala** [dazinovic/neural-rgbd-surface-reconstruction#3]
Hi, thanks for sharing this fantastic work!
Would you have any plan to release the processed scanNet data for the experiments? Especially for the computed camera params, train/val pose split and filtered depth images, which could be good starting point for others to compare fairly.

**Comment by dazinovic** [comment]
Hi Guptajakala,

I do not plan to release any ScanNet data (please refer to the official ScanNet website to obtain the data). There is no train/val split here. Every 'train_skip'th pose (e.g. every pose or every 4th pose) is used to optimize the SDF. The trainval_poses.txt naming scheme is an artifact from an earlier stage in the project and I forgot to rename it for the code release.

To get the filtered depth images, you can run https://github.com/angeladai/spsg/blob/master/datagen/src/CameraUtil.h#L25 with sigmaD = 2.0 and sigmaR = 0.1.

If you need help with comparisons for your paper (e.g. comparison of the camera trajectories), feel free to send me an email.

**Comment by soumyadipm** [comment]
Can you guys please help me to run this code on ScanNet? Struggling for last two weeks.

**Comment by songlin** [comment]
@soumyadipm Hi, did you manage to run on ScanNet? Help is appreciated.
