### ISSUE TITLE
How to sample points on mesh?

### ISSUE THREAD

**Issue by waveviewer** [dazinovic/neural-rgbd-surface-reconstruction#30]
Thanks for this great job.

I am confused about the evaluation part of the paper, the F-score specifically. As the supplemental material said, the culled mesh is sampled with a density of 1 point per $cm^2$ . I have no idea about sampling. Can you provide your script or other tools? 

Any help would be appreciated.

**Comment by dazinovic** [comment]
I used trimesh to calculate the area of the scene and to sample points on the mesh (trimesh has a sample function that accepts the total number of points to sample).

**Comment by waveviewer** [comment]
Thanks for reply, I successfully sampled the model and calculated the F-score using Trimesh.
