### ISSUE TITLE
cannot download data

### ISSUE THREAD

**Issue by kyj24182** [dazinovic/neural-rgbd-surface-reconstruction#36]
Seems like the link : http://kaldir.vc.in.tum.de/neural_rgbd/neural_rgbd_data.zip is broken.

Could you please upload the data to some place else (maybe on gdrive?)

**Comment by dazinovic** [comment]
The server is down at the moment. We are working on a fix.

**Comment by dhuwzj** [comment]
@dazinovic Looking forward to your fix...

**Comment by dazinovic** [comment]
@kyj24182 @dhuwzj 

Could you check again if the download links work?

**Comment by dhuwzj** [comment]
@dazinovic It works！Thank you!
