### ISSUE TITLE
There is a problem to download your dataset

### ISSUE THREAD

**Issue by czlyyr** [dazinovic/neural-rgbd-surface-reconstruction#8]
I can't download your dataset, maybe there is something wrong with your link. Could you please help me, thanks.

**Comment by dazinovic** [comment]
I just tested it from outside the university and it works. Are you sure your browser isn't blocking the download?

**Comment by HtForBetterLife** [comment]
> I just tested it from outside the university and it works. Are you sure your browser isn't blocking the download?

I still can't download the dataset. I don't know why.
and the network and brower works well.

**Comment by HtForBetterLife** [comment]
> 

I solve the problem by opening a new browser window with the download link.
The problem may be caused by HTTP protocol conflict between GitHub and dataset link.
